FissaBissa/FissaBissa/Controllers/AnimalsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using FissaBissa.Models;
using FissaBissa.Utilities;
using Microsoft.AspNetCore.Authorization;
using FissaBissa.Repositories;

namespace FissaBissa.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AnimalsController : Controller
    {
        private readonly IAnimalRepository _animalRepo;
        private readonly IAccessoryRepository _accessoryRepo;

        public AnimalsController(IAnimalRepository animalRepo, IAccessoryRepository accessoryRepo)
        {
            _animalRepo = animalRepo;
            _accessoryRepo = accessoryRepo;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _animalRepo.Get());
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _animalRepo.Get(id.Value);

            if (entity == null)
            {
                return NotFound();
            }

            return View(entity);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewData["TypeId"] = new SelectList(await _animalRepo.GetTypes(), "Id", "Name");
            ViewData["Accessories"] = new MultiSelectList(await _accessoryRepo.Get(), "Id", "Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,TypeId,Price,Image,Accessories")]
            AnimalModel model)
        {
            var path = await FileUtilities.StoreImage(nameof(model.Image), model.Image, ModelState);

            if (ModelState.IsValid)
            {
                await _animalRepo.Create(model, path);

                return RedirectToAction(nameof(Index));
            }

            ViewData["TypeId"] = new SelectList(await _animalRepo.GetTypes(), "Id", "Name", model.TypeId);
            ViewData["Accessories"] = new MultiSelectList(await _accessoryRepo.Get(), "Id", "Name", model.Accessories);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _animalRepo.Get(id.Value);

            if (entity == null)
            {
                return NotFound();
            }

            ViewData["TypeId"] = new SelectList(await _animalRepo.GetTypes(), "Id", "Name", entity.TypeId);
            ViewData["Accessories"] = new MultiSelectList(await _accessoryRepo.Get(), "Id", "Name",
                entity.Accessories.Select((a) => a.AccessoryId).ToList());

            return View(entity.Transform());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Guid id, [Bind("Id,Name,TypeId,Price,Image,Accessories")]
            AnimalModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            var path = await FileUtilities.StoreImage(nameof(model.Image), model.Image, ModelState);

            if (ModelState.IsValid)
            {
                await _animalRepo.Update(model, path);

                return RedirectToAction(nameof(Index));
            }

            ViewData["TypeId"] = new SelectList(await _animalRepo.GetTypes(), "Id", "Name", model.TypeId);
            ViewData["Accessories"] = new MultiSelectList(await _accessoryRepo.Get(), "Id", "Name", model.Accessories);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _animalRepo.Get(id.Value);

            if (entity == null)
            {
                return NotFound();
            }

            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _animalRepo.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

FissaBissa/FissaBissa/Controllers/ReservationsController.cs
using System;
using System.Threading.Tasks;
using FissaBissa.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FissaBissa.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReservationsController : Controller
    {
        private readonly IReservationRepository _reservationRepo;

        public ReservationsController(IReservationRepository reservationRepo)
        {
            _reservationRepo = reservationRepo;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _reservationRepo.Get());
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _reservationRepo.Get(id.Value);

            if (entity == null)
            {
                return NotFound();
            }

            return View(entity);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = await _reservationRepo.Get(id.Value);

            if (entity == null)
            {
                return NotFound();
            }

            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            await _reservationRepo.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

FissaBissa/FissaBissa/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FissaBissa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FissaBissa</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Animals" asp-action="Index">@Localizer["Animals"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Accessories" asp-action="Index">@Localizer["Accessories"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Reservations" asp-action="Index">@Localizer["Reservations"]</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container my-4">
            <span class="d-inline-block mr-3">
                &copy; 2020 - FissaBissa
            </span>
            @await Html.PartialAsync("_SelectLanguagePartial")
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FissaBissa/FissaBissa/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem {Value = c.Name, Text = c.DisplayName})
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<form style="display: inline-block" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl" method="post">
    <select name="culture" onchange="this.form.submit()" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
</form>